### ISSUE TITLE
The 'bin' icons do not work - i cannot delete items from character sheet

### ISSUE THREAD

**Issue by MinkGoblin** [Foxfyre/expanse#11]
**Describe the bug**
The 'bin' icons do not work - i cannot delete items from character sheet
**To Reproduce**
1. Go to the equipment page of the Actor sheet for Expanse AGE
2. Click on drag a weapon (eg, únarmed combat'from Expanse AGE quickstart)
3. Scroll down to item
4. clicking the bin does not remove the item
**Expected behavior**
the item to be removed from Actor sheet when the bin is closed
None of the bins icon work, ie the bins next to talents in the talent & specialisation tab do not work either
**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 11
 - Browser Chrome
 - 97.0.4692.71

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Foxfyre** [comment]
@MinkGoblin what version of Foundry are you using?

**Comment by MinkGoblin** [comment]
Foundry version 9 build 242
Expanse RPG (AGE) 0.7.2

**Comment by Foxfyre** [comment]
> Foundry version 9 build 242 Expanse RPG (AGE) 0.7.2

Updating the Expanse system to 0.8.1 should fix that issue

**Comment by MinkGoblin** [comment]
fixed, tyvm
