### ISSUE TITLE
A 'maximum fortune' field

### ISSUE THREAD

**Issue by MinkGoblin** [Foxfyre/expanse#15]
**Is your feature request related to a problem? Please describe.**
Currently there is only one field to record fortune. It's easy to lose track of maximum when it gets modified so frequently.
**Describe the solution you'd like**
An additional field that can be edited to record the maximum fortune level
**Describe alternatives you've considered**

**Additional context**

**Comment by KiraTsunayoshi** [comment]
Not a solution, but as a workaround we double entry in the Fortune field.
Example "2330" means current Fortune of 23, out of 30 Max.

**Comment by Foxfyre** [comment]
Feature added in 0.8.5
