### ISSUE TITLE
Allow to add items in the different lists from the character sheet

### ISSUE THREAD

**Issue by gdelmee** [Foxfyre/expanse#16]
**Is your feature request related to a problem? Please describe.**
By default, we can't add items in the different lists. It is mandatory to use the starter kit compendium to fulfil the character sheet.
Building a custom character, not all items are available.

**Describe the solution you'd like**
Add a button to create an empty item in the current list (stun, talent, weapon, armor, …).

**Describe alternatives you've considered**
I've used the drag & drop from the items in the compendium and then edit it.
As the compendium doesn't provide each of every type (for example, no armor), this is a huge limitation, by now. For example, there are no armors in the current compendium, so we can't set armors to characters.

**Comment by Foxfyre** [comment]
@gdelmee "As the compendium doesn't provide each of every type (for example, no armor), this is a huge limitation, by now. For example, there are no armors in the current compendium, so we can't set armors to characters."

Armor is an item type in the items list which means you can create one then set its stats for future use. The Quickstart only contains items that are present in the quickstart.  The full core compendium is currently a WIP. 

Creating items on the actor will be in the next update (0.8.2). It is available for testing now if you clone this repo.
