### ISSUE TITLE
Save doesn't work on Field (Biography & Notes)

### ISSUE THREAD

**Issue by Pyngwie** [Foxfyre/expanse#18]
**Describe the bug**
Save doesn't work on Biography (description, relationship and goals) & Notes fields. 
Once I've written something and I click on the save button, my text disappears.

**Expected behavior**
The text should be saved et remain into the field after saving.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Window 10
 - Browser [e.g. chrome, safari] : Chrome
 - Version : Foundry 0.9, The Expanse 0.8.1

**Comment by Foxfyre** [comment]
@Pyngwie thank you for pointing this out. An update will be available soon.

**Comment by Lebo77** [comment]
This is still not working. 

Hitting save or just closing the window causes the loss of the contents of any thing on the Biography tab.

**Comment by Lebo77** [comment]
Also happens on the notes field.

I am on version 8.2.
