### ISSUE TITLE
Wrong image size in NPC character sheets

### ISSUE THREAD

**Issue by Pyngwie** [Foxfyre/expanse#20]
**Describe the bug**
when putting an image in NPCs character sheets, it does'nt appear with the proper size.
The  default size seems to be fixed.

**Expected behavior**
When uploading an image I should see it entirely.

**Screenshots**
![issue_character_image](https://user-images.githubusercontent.com/76539732/152610687-38cb0c5a-2db9-4d28-b904-9990f0c7f164.JPG)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]Windows 10
 - Chrome  98.0.4758.82
 - Foundry v9
 - The Expanse 0.8.2

**Comment by Foxfyre** [comment]
Fix implimented in 0.8.4
