### ISSUE TITLE
Initiative button in Combat Tracker actually makes the Actor's Dexterity check, vice just rolling 3d6

### ISSUE THREAD

**Issue by KiraTsunayoshi** [Foxfyre/expanse#22]
**Is your feature request related to a problem? Please describe.**
Currently rolling initiative in the Combat Tracker just rolls 3d6.  

**Describe the solution you'd like**
When using the Combat Tracker to roll initiative for an Actor, it makes a Dexterity check using the Actor's Dexterity stat.  GM will still need to manually update if an Actor has the Dex(Initiative) Focus, or has an initiative modifier, but at least the check will be done using the Actor's stat value instead of just 3d6.  So will be correct for most Actors w/o the Focus or any init mods.

**Describe alternatives you've considered**
To do it correctly, current each player needs to make a Dex check manually, then the GM needs to update each Actor's initiative in the Combat Tracker.  This is time consuming and really slows down the 1st round of combat.

**Additional context**
The Expanse rule book, p.83, describes how Initiative is rolled

**Comment by EnGy1968** [comment]
Works in 0.8.4...

**Comment by Foxfyre** [comment]
Issue solved in 0.8.4
