### ISSUE TITLE
User cannot equip both shield and armor in the character sheet

### ISSUE THREAD

**Issue by jamakkon** [Foxfyre/expanse#25]
**Describe the bug**
If you equip both shield and armor, which are placed in different sections in the character sheet, you will get warning "You can have only one piece of armour equipped at one time. Please remove your current armor before continuing." (Note the alternating spelling armour/armor)

**To Reproduce**
1. Go to 'Equipment' tab in the character sheet.
2. Click on '+' to add new Armor. Click the checkbox for 'Equipped'.
2. Click on '+' to add new Shield. Click the checkbox for 'Equipped'.
4. See error pop-up: "You can have only one piece of armour equipped at one time. Please remove your current armor before continuing."

**Expected behavior**

There should not be an error message. AFAIK, the rules do not prohibit simultaneous use of a shield and an armor. Riot gear would be useless.

**Desktop (please complete the following information):**
 - OS: macOS 12.3.1
 - Browser: Firefox
 - Version: 99
 - The Expanse RPG (AGE): 0.8.2
 -  Foundry VTT: v9 (build 268)

**Additional context**
Do the rules prohibit equipping two armors, or is it a house rule?

**Comment by Foxfyre** [comment]
Issue solved in 0.8.3
