### ISSUE TITLE
Instable NPC Token Sheet behavior

### ISSUE THREAD

**Issue by theczarek** [Foxfyre/expanse#29]
**Describe the bug**
NPC Sheet for unlinked tokkens (Token propoerty "Link character data" unchecked) cannot be edited when there is an item entity (armour or weapon) added to it. Also  dice rolls cannot be made (not alway but in most casses) and close button on sheet window is inactive. Tested and reproduced on word without any modules added.

**To Reproduce**
1. Create NPC
2. Edit tooken prototype by ucheck "Link character data"
3. Add weapon and/or armour
4. Drag NPC's token to the screen
5. Open sheet via tokken
6. Try edit eg. add/chcnge focuses, try rollin, closing shhe

**Expected behavior**
Ability to edit, roll and close 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Alpine (cloud hosting
 - Browser Chrome
 - Version  100.0.4896.127 
 - Foundry 9.xxx 

**Additional context**

**Comment by Foxfyre** [comment]
Unable to duplicate issue. Try updating to latest Expanse system version (0.8.5) and see if that works.

**Comment by jabelardo** [comment]
I have the same problem, 

OS: Linux ubuntu (cloud hosting)
Browser Edge
Version 101.0.1210.32 (Official build) (64-bit)
Foundry 9.269
Expanse 0.8.4

**Comment by altered-beast** [comment]
I and the rest of my group are having the same issue 
in addition ive noticed that both memory and cpu increase significantly while these issues are occurring

OS: Linux debian (in lxc container)
Browser: firefox  100.0.1 (64-bit) 
foundry 9
expanse 0.8.5

**Comment by Foxfyre** [comment]
Is this issue still present in V10/ Expanse 1.0.0?

**Comment by ahkneipp** [comment]
I have not been able to reproduce the issue in the new version, and I was experiencing it in previous versions
