### ISSUE TITLE
Armor values only partly fixed and new problem

### ISSUE THREAD

**Issue by soulmanagement** [Foxfyre/expanse#32]
**Describe the bug**
Version 0.8.4. fixed a major part of the issues I had, but it did not fix all. Additionally, something new came up.
Armor values are now indeed added properly when the "Equipped"-box is checked. But Speed ist still unmodified by the armor's penalty.
Additionally, only the most recently added armor works this way, armors added earlier do not work any longer, their values are not added properly anymore.
And then additionally, one can check the "Equipped"-boxes of all armors at the same time! It should not be possible to wear more than one armor ;-)

**To Reproduce**
1. Add an armor to your character's equipment section
2. Check the armor's "Equipped"-box
3. See that armor values (protection and penalty) are now added to the static part of the character sheet, as it should be
4. Also see, that if the armor has a penalty greater than zero, the penalty is still NOT deducted from Speed
5. Uncheck the armor's "Equipped"-box
6. Add another armor to the character's equipment section
7. Repeat 2. to 5. with the new armor
8. Now try 2. to 5. again with the first armor and see, that NO armor values are added to the character sheet's static part anymore
9. Obviously, only the armor that has been added last works at all, but still with unchanged Speed-value
10. Try to check the "Equipped"-boxes of all armors on the character and see that this works

**Expected behavior**
A character should be able to have several armors listed on his character sheet, with all of them working properly (not only the latest one), and it should not be possibe to check all armors as 'equipped' at the same time. Either it should be that you can not check a box once another is checked already, or it should be that checking a box will uncheck the other armor's box.
Speed should be changed according to the armor's penalty value, once the armor is in use.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: No browser, this happens directly in Foundry VTT as a gamemaster
 - Version: Foundry 9.269  /  Expanse Game System 0.8.4.

**Additional context**
I am sorry to kind of re-open this, but without the fix to the non-appearing armor values I was unable to see that only one armor works. Also, there is still the fix to Speed missing.
But thanks for working on this to give us a neat system to experience The Expanse with :-)

**Comment by EnGy1968** [comment]
Hey!

Just IMHO there is always a little risk in focusing on automation issues more than on core functionalities.
E.g. the actor sheet should provide all the data necessary to run the game, but its a pretty tough thing to represent all the possible cross- and roll effects. The Expanse rule system gives many many options, but this creates a hell for programming,
So one thing really might be needed is a pretty generic roll setup, which enables the gamemaster to adapt to all those specialties (armor, item qualities, action, stunt or talent impact, environment, target size etc...) just like he does in actual gameplay.  Additional automation parts could be set upon this basic functionality.   
So, how could a most flexible roll dialogue could look like?

**Comment by soulmanagement** [comment]
If Foundry-VTT does not take some of my workload, then I see no reason to use it and go back to make online sessions using Teamspeak for audio and Telegram for text and pictures, sending PDF-charactersheets (which I make in Excel where the stuff IS calculated automatically) to the participants. That worked before and it will work again.
Having to remind the players of calculating some stuff that could be automated, does not take anything away from my workload.
I have seen a modifiable dice-roll dialogue in the Conan game system for Foundry-VTT, and it is not to my liking, because there are too many options which are not explained properly...

**Comment by EnGy1968** [comment]
It's less about having no automation, but about having a functionality first, which is able to deal with all the options not automated yet. Of course any automation implemented is useful. Maybe also this stunt-thing someday.

**Comment by Poetisle** [comment]
Since this seems mildly active. If you guys are capable of pulling my changes. Let me know and try out my fix. I added a penalty box for applying the armor penalty specifically to dex rolls.

**Comment by soulmanagement** [comment]
That may be a fix for the missing values, but not for the other bugs I dug up ;-)

**Comment by Foxfyre** [comment]
This should now be addressed with 1.0.0 and implementation of #40
