### ISSUE TITLE
Requirements for Talents not being saved

### ISSUE THREAD

**Issue by aNjaSqurl** [Foxfyre/expanse#7]
**Describe the bug**
Information entered into the Requirements field for Talents is not being saved. 

**To Reproduce**
Add text to Requirements field for a Talent
Close popup for Talent
Reopen
Text for other fields will remain but Requirements will be gone. 

**Expected behavior**
Text in Requirements field should remain after the popup is closed. 

**Screenshots**
![image](https://user-images.githubusercontent.com/96093812/145916694-11c06ef5-7de5-4eae-ba91-b8da099c8523.png)
With text added

![image](https://user-images.githubusercontent.com/96093812/145916798-bf7f18fc-b545-4353-b9c6-fc2b887e54b2.png)
after closing and reopening

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Chrome
 - Version 96.0.4664.110 (Official Build) (64-bit)

**Additional context**
This is my first time I've posted here so if I've done something wrong let me know. I can be reached on the Green Ronin Discord

**Comment by Foxfyre** [comment]
Bug fixed in V0.7.2
